In [1]:
import pandas as pd

In [12]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns = ["A", "B", "C"], index = ["x", "y", "z"])

In [13]:
df.head(1)

   A  B  C
x  1  2  3

In [14]:
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [15]:
df.tail()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [16]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [17]:
df.index.tolist()

['x', 'y', 'z']

In [18]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [20]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [21]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [24]:
df['A'].unique()

array([1, 4, 7])

In [26]:
df.shape

(3, 3)

In [27]:
df.size

9

In [28]:
 #csv = comma separeted files

In [93]:
coffee = pd.read_csv('./assests/coffee.csv')

In [32]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [33]:
results = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv")

In [34]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [35]:
bios = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv")

In [38]:
coffee.sample(10, random_state = 1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [40]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [42]:
coffee.loc[[0, 1, 5]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [43]:
coffee.loc[5:]

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [44]:
coffee.loc[5:8]

         Day Coffee Type  Units Sold
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45

In [47]:
coffee.loc[:, ["Day", "Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [49]:
coffee.iloc[0:2, 0:2] # iloc = index - loc(uses index )

      Day Coffee Type
0  Monday    Espresso
1  Monday       Latte

In [50]:
# in iloc the upper index is not inclusive, but it was inclusive with .loc

In [51]:
coffee.loc[0:2]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [55]:
#coffee.index = coffee["Day] -> replace the indices in data frame by values in column "Day"

In [58]:
coffee = coffee.reset_index(drop = True)

In [59]:
coffee.loc[1, "Units Sold"] = 10

In [60]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        10.0
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0
14        NaN         NaN        10.0

In [61]:
coffee.at[0, "Units Sold"]

np.float64(25.0)

In [63]:
coffee.iat[0, 2] # iat = integer at

np.float64(25.0)

In [64]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
14          NaN
Name: Day, dtype: object

In [65]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
14          NaN
Name: Day, dtype: object

In [66]:
coffee.sort_values("Units Sold", ascending = False)

          Day Coffee Type  Units Sold
12     Sunday    Espresso        45.0
10   Saturday    Espresso        45.0
8      Friday    Espresso        45.0
6    Thursday    Espresso        40.0
9      Friday       Latte        35.0
4   Wednesday    Espresso        35.0
13     Sunday       Latte        35.0
11   Saturday       Latte        35.0
2     Tuesday    Espresso        30.0
7    Thursday       Latte        30.0
5   Wednesday       Latte        25.0
0      Monday    Espresso        25.0
3     Tuesday       Latte        20.0
1      Monday       Latte        10.0
14        NaN         NaN        10.0

In [67]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        10.0
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0
14        NaN         NaN        10.0

In [70]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending = [0, 1]) ## in case of tie in units sold, use coffee type and descending in units sold and ascending in coffee type

          Day Coffee Type  Units Sold
8      Friday    Espresso        45.0
10   Saturday    Espresso        45.0
12     Sunday    Espresso        45.0
6    Thursday    Espresso        40.0
4   Wednesday    Espresso        35.0
9      Friday       Latte        35.0
11   Saturday       Latte        35.0
13     Sunday       Latte        35.0
2     Tuesday    Espresso        30.0
7    Thursday       Latte        30.0
0      Monday    Espresso        25.0
5   Wednesday       Latte        25.0
3     Tuesday       Latte        20.0
1      Monday       Latte        10.0
14        NaN         NaN        10.0

In [74]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("\n") 
# its slow, not optimized, don't use often

0
Day              Monday
Coffee Type    Espresso
Units Sold         25.0
Name: 0, dtype: object


1
Day            Monday
Coffee Type     Latte
Units Sold       10.0
Name: 1, dtype: object


2
Day             Tuesday
Coffee Type    Espresso
Units Sold         30.0
Name: 2, dtype: object


3
Day            Tuesday
Coffee Type      Latte
Units Sold        20.0
Name: 3, dtype: object


4
Day            Wednesday
Coffee Type     Espresso
Units Sold          35.0
Name: 4, dtype: object


5
Day            Wednesday
Coffee Type        Latte
Units Sold          25.0
Name: 5, dtype: object


6
Day            Thursday
Coffee Type    Espresso
Units Sold         40.0
Name: 6, dtype: object


7
Day            Thursday
Coffee Type       Latte
Units Sold         30.0
Name: 7, dtype: object


8
Day              Friday
Coffee Type    Espresso
Units Sold         45.0
Name: 8, dtype: object


9
Day            Friday
Coffee Type     Latte
Units Sold       35.0
Name: 9, dtype: object


10
Day            Saturday
Coffee Type    Espresso
Units Sold         45.0
Name: 10, dtype: object


11
Day            Saturday
Coffee Type       Latte
Units Sold         35.0
Name: 11, dtype: object


12
Day              Sunday
Coffee Type    Espresso
Units Sold         45.0
Name: 12, dtype: object


13
Day            Sunday
Coffee Type     Latte
Units Sold       35.0
Name: 13, dtype: object


14
Day             NaN
Coffee Type     NaN
Units Sold     10.0
Name: 14, dtype: object

In [75]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [80]:
bios.loc[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA'), ['name', 'born_date', 'height_cm']]

                    name   born_date  height_cm
5781      Tommy Burleson  1952-02-24      223.0
6722    Shaquille O'Neal  1972-03-06      216.0
6937      David Robinson  1965-08-06      216.0
123850    Tyson Chandler  1982-10-02      216.0

In [81]:
bios[bios['name'].str.contains("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [82]:
bios[bios['name'].str.contains("keith|patrick", case = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [85]:
bios.query('born_country == "USA" & born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

In [86]:
coffee['price'] = 4.99

In [89]:
import numpy as np
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso        25.0   4.99       3.99
1     Monday       Latte        10.0   4.99       5.99
2    Tuesday    Espresso        30.0   4.99       3.99
3    Tuesday       Latte        20.0   4.99       5.99
4  Wednesday    Espresso        35.0   4.99       3.99

In [90]:
coffee.drop(columns = ["price"])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso        25.0       3.99
1      Monday       Latte        10.0       5.99
2     Tuesday    Espresso        30.0       3.99
3     Tuesday       Latte        20.0       5.99
4   Wednesday    Espresso        35.0       3.99
5   Wednesday       Latte        25.0       5.99
6    Thursday    Espresso        40.0       3.99
7    Thursday       Latte        30.0       5.99
8      Friday    Espresso        45.0       3.99
9      Friday       Latte        35.0       5.99
10   Saturday    Espresso        45.0       3.99
11   Saturday       Latte        35.0       5.99
12     Sunday    Espresso        45.0       3.99
13     Sunday       Latte        35.0       5.99
14        NaN         NaN        10.0       5.99

In [91]:
coffee.drop(columns = ["price"], inplace = True)

In [92]:
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso        25.0       3.99
1      Monday       Latte        10.0       5.99
2     Tuesday    Espresso        30.0       3.99
3     Tuesday       Latte        20.0       5.99
4   Wednesday    Espresso        35.0       3.99
5   Wednesday       Latte        25.0       5.99
6    Thursday    Espresso        40.0       3.99
7    Thursday       Latte        30.0       5.99
8      Friday    Espresso        45.0       3.99
9      Friday       Latte        35.0       5.99
10   Saturday    Espresso        45.0       3.99
11   Saturday       Latte        35.0       5.99
12     Sunday    Espresso        45.0       3.99
13     Sunday       Latte        35.0       5.99
14        NaN         NaN        10.0       5.99